In [1]:
import numpy as np
from scipy.stats import gmean

In [6]:
m = np.array([1.5,1.5,1.5,3,3,3,3])
print(gmean(m))
wt = np.array([1,1,1,1,1,.5,.5,.5])
print(gmean(wt))
print(gmean(m)/gmean(wt))

2.2289914337054224
0.7711054127039704
2.890644258207456


In [7]:
b = np.array([np.log(.799),np.log(.531),np.log(.664), np.log(2.891)])
A = np.array([[1,2/7-4/8,2/7-5/8,2/7-5/8],
              [2/6-5/9,1,3/6-4/9,3/6-4/9],
              [2/7-5/8,3/7-3/8,1,2/7-5/8],
              [2/7-5/8,3/7-3/8,2/7-5/8,1]])

print(A)

[[ 1.         -0.21428571 -0.33928571 -0.33928571]
 [-0.22222222  1.          0.05555556  0.05555556]
 [-0.33928571  0.05357143  1.         -0.33928571]
 [-0.33928571  0.05357143 -0.33928571  1.        ]]


In [8]:
x = np.linalg.solve(A,b)
print(np.exp(x))

[0.99990284 0.49952575 1.00053004 3.0009623 ]
